M48
; DRILL file {KiCad 8.0.1} date 2024-08-17T16:07:05+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-08-17T16:07:05+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.700
%
G90
G05
T1
X77.2Y-65.8
X77.2Y-108.0
X161.4Y-65.8
X161.4Y-108.0
T2
X84.75Y-75.95
X153.85Y-75.95
M30
